services:
  test-runner:
    build:
      context: .
      target: test-runner
    command: npm run test
    environment:
      AWS_FAKE_ENDPOINT: http://localstack:4566
      AWS_REGION: eu-west-1
      SOURCE_BUCKET: source-bucket
      DEST_BUCKET: dest-bucket
    depends_on:
      - localstack

  localstack:
    image: localstack/localstack
    ports:
      - '4566:4566'
    environment:
      SERVICES: lambda,s3
      DOCKER_HOST: unix:///var/run/docker.sock
      LAMBDA_DOCKER_NETWORK: testable-lambda-example_default
      AWS_REGION: eu-west-1
      DEBUG: 1
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

version: '3.9'
